[project]
name = "producer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "aio-pika>=9.5.5",
    "aiohttp",
    "httpx[http2]>=0.24.0"
]
