kind: Kustomization

resources:
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.83.0/bundle.yaml # prometheus operator
  - service-account.yaml
  - cluster-role.yaml
  - prometheus.yaml