---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: default
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: devops
  podMonitorSelector:
    matchLabels:
      team: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus # Name of the ClusterRole created above
subjects:
- kind: ServiceAccount
  name: prometheus # Name of the ServiceAccount created above
  namespace: default # Namespace of the ServiceAccount