apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{scaled_object_name}"
  namespace: "{operator_namespace}"
  labels:
    kopf.operator.rabbitmq_queue: "{queue_name}"
    app.kubernetes.io/managed-by: "rabbitmq-keda-operator"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{target_deployment_name}"
  pollingInterval: {polling_interval}
  cooldownPeriod: {cooldown_period}                          
  minReplicaCount: {min_replica_count}
  maxReplicaCount: {max_replica_count}
  advanced:                                       
    restoreToOriginalReplicaCount: true           
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: "{queue_name}"
      mode: QueueLength
      value: "10"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn