apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{scaled_object_name}"
  namespace: "{operator_namespace}"
  labels:
    kopf.operator.rabbitmq_queue: "{queue_name}"
    app.kubernetes.io/managed-by: "rabbitmq-keda-operator"
spec:
  scaleTargetRef:
    name: "{target_deployment_name}"
  pollingInterval: {polling_interval}
  minReplicaCount: {min_replica_count}
  maxReplicaCount: {max_replica_count}
  triggers:
  - type: rabbitmq
    metadata:
      queueName: "{queue_name}"
      host: "{rabbitmq_host}"
      mode: QueueLength
      value: "20"