FROM docker-registry-remote.artifactory-espoo1.int.net.nokia.com/locustio/locust:latest

COPY FROM docker-registry-remote.artifactory-espoo1.int.net.nokia.com/locustio/locust:latest

CMD ["-f", "/mnt/locust/", "--class-picker"]
