[project]
name = "subcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aio-pika>=9.5.5",
    "fastapi[standard]>=0.115.12",
    "lorem-text>=3.0",
    "requests>=2.31.0",
]
