SERVICE_REQUEST_EXCHANGE_NAME = "service.request"
CLIENT_REQUEST_EXCHANGE_NAME = "client.request"

SERVICE_RESPONSE_EXCHANGE_NAME = "service.response"

CLIENT_RESPONSE_QUEUE_NAME_PREFIX = "client.response"

DATABASE_REQUEST_QUEUE_NAME = "event_logs"
DATABASE_RESPONSE_QUEUE_NAME = "event_logs"
