apiVersion: apps/v1
kind: Deployment
metadata:
  name: step-load-locust
  namespace: locust
  labels:
    app: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
        - name: locust
          image: localhost:32000/locust
          ports:
            - containerPort: 8089
          args:
            - -f
            - /mnt/locust/locustfile.py,/mnt/locust/shape_classes/gradual_load.py
            - --host=http://producer-service.default.svc.cluster.local:8000
