apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
data:
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "admin"
  OPERATOR_NAMESPACE: "default"
  RABBITMQ_POLL_INTERVAL_SECONDS: "15"
  KEDA_MIN_REPLICAS: "0"
  KEDA_MAX_REPLICAS: "20"
  KEDA_QUEUE_LENGTH_THRESHOLD: "10"