apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: default
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: controller
          image: localhost:32000/controller:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: controller-config