apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: locust
  labels:
    app: locust
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: locust
  type: LoadBalancer