apiVersion: v1
kind: Service
metadata:
  name: database-helper-service
  namespace: default
  labels:
    app: database-helper-service
spec:
  selector:
    app: database-helper
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000