apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-constant-low-load
  namespace: locust
  labels:
    app: locust
    locust-test: "constant-low-load"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      locust-test: "constant-low-load"
  template:
    metadata:
      labels:
        app: locust
        locust-test: "constant-low-load"
    spec:
      containers:
        - name: locust
          image: localhost:32000/locust
          ports:
            - containerPort: 8089
          args:
            - -f
            - /mnt/locust/locustfile.py,/mnt/locust/shape_classes/constant_low_load.py
            - --host=http://producer-service.default.svc.cluster.local:8000
