[project]
name = "controller-operator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "kopf>=1.38.0",
    "kubernetes>=32.0.1",
    "requests>=2.32.3",
]
