# operator-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmq-keda-scaler-operator
rules:
- apiGroups: ["keda.sh"]
  resources: ["scaledobjects"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rabbitmq-keda-scaler-operator-binding
subjects:
- kind: ServiceAccount
  name: rabbitmq-keda-operator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: rabbitmq-keda-scaler-operator
  apiGroup: rbac.authorization.k8s.io