apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-spike-load
  namespace: locust
  labels:
    app: locust
    locust-test: "spike"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      locust-test: "spike"
  template:
    metadata:
      labels:
        app: locust
        locust-test: "spike"
    spec:
      containers:
        - name: locust
          image: localhost:32000/locust
          ports:
            - containerPort: 8089
          args:
            - -f
            - /mnt/locust/locustfile.py,/mnt/locust/shape_classes/spike_load.py
            - --host=http://producer-service.default.svc.cluster.local:8000
