apiVersion: v1
kind: Service
metadata:
  name: locust-metrics-exporter
  namespace: locust
  labels:
    app: locust-metrics-exporter
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9646
      targetPort: http-metrics
  selector:
    app: locust-metrics-exporter
