[project]
name = "controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aio-pika>=9.5.5",
    "fastapi[standard]>=0.115.12",
    "kopf>=1.38.0",
    "kubernetes>=32.0.1",
    "pydantic-settings>=2.9.1",
]
