apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
data:
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "admin"
  CONTROLLER_SERVICE_URL: "http://controller-service:8000"