apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-static
  labels:
    app: producer
    version: static
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
      version: static
  template:
    metadata:
      labels:
        app: producer
        version: static
    spec:
      containers:
        - name: producer-static
          image: localhost:32000/producer
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: producer-config
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 1024Mi