apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret-http
stringData:
  host: http://admin:admin@rabbitmq.default.svc.cluster.local:15672/
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn-http
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret-http
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: producer-queue-scaledobject
  namespace: default
  labels:
      app.kubernetes.io/managed-by: "rabbitmq-keda-operator"
spec:
  scaleTargetRef:
    apiVersion: apps/v1                           # Default apps/v1 
    kind: Deployment                              # Default Deployment
    name: producer
  pollingInterval: 5                              # Optional. Default: 30 seconds
  cooldownPeriod:  30                             # Optional. Default: 300 seconds
  minReplicaCount: 0                              # Default: 0
  maxReplicaCount: 10                             # Default: 100
  advanced:                                       # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true           # Optional. Default: false
  triggers:
  - type: rabbitmq
    metadata:
      protocol: http
      queueName: ^client\.response\..*
      mode: QueueLength
      value: "10"
      useRegex: "true"
      operation: sum
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn-http