apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
stringData:
  host: amqp://admin:admin@rabbitmq.default.svc.cluster.local:5672
  vhostName: /
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
    - parameter: vhostName
      name: keda-rabbitmq-secret
      key: vhostName
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-queue-scaledobject
  namespace: default
  labels:
      app.kubernetes.io/managed-by: "rabbitmq-keda-operator"
spec:
  scaleTargetRef:
    apiVersion: apps/v1                           # Default apps/v1 
    kind: Deployment                              # Default Deployment
    name: consumer
  activationValue: 0                              # Optional. Default: 0, If the minimum replicas is >= 1, the scaler is always active and the activation value will be ignored.
  pollingInterval: 30                             # Optional. Default: 30 seconds
  cooldownPeriod:   120                           # Optional. Default: 300 seconds
  minReplicaCount: 1                              # Default: 0
  maxReplicaCount: 10                             # Default: 100
  advanced:                                       # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true           # Optional. Default: false
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: service.request.consumer
      mode: QueueLength
      value: "20"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn