apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
data:
  CONSUMER_SERVICE_URL: "http://consumer-service:8000"
  CONTROLLER_SERVICE_URL: "http://controller-service:8000"
  RABBITMQ_URL: "amqp://admin:admin@rabbitmq:5672/"
  RABBITMQ_PREFETCH_COUNT: "50"
  TIME_TO_FIRST_TOKEN: "36"
  INTER_TOKEN_LATENCY: "5"
  OUTPUT_LENGTH: "200"
  REQUEST_LATENCY: "1000" # close to TIME_TO_FIRST_TOKEN + INTER_TOKEN_LATENCY * OUTPUT_LENGTH
  MAX_CONCURRENT_REQUESTS: "25"
  ENABLE_STREAMING: "True"
