apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cadvisor
  namespace: default # Or your Prometheus namespace
  labels:
    team: devops # Must match your Prometheus CR's selector
spec:
  podMetricsEndpoints:
  - port: http # Name of the secure port on Kubelet (usually 10250)
    portNumber: 8080
    path: /metrics # cAdvisor metrics path
    interval: 5s
  selector:
    # This selects the Kubelet service, which typically doesn't exist as a formal Service.
    # Instead, we rely on the Prometheus Operator's ability to discover Kubelets
    # via the `role: node` in its `kubernetes_sd_configs`.
    # This selector is often empty or targets a specific label if your cluster management
    # creates a Service for Kubelets. For `kube-prometheus-stack`, it often works implicitly.
    matchLabels:
      app: cadvisor
  namespaceSelector:
    matchNames:
      - cadvisor