apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: default # Or the namespace where your Prometheus instance expects ServiceMonitors
  labels:
    team: devops # This label is crucial if your Prometheus instance uses a selector like `serviceMonitorSelector`
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  namespaceSelector:
    any: true
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 5s # How often Prometheus should scrape these metrics
